# .github/workflows/deploy.yml
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: PHP セットアップ
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Composer install
        run: composer install --no-progress --no-suggest --optimize-autoloader

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --configuration phpunit.xml

      - name: Node.js セットアップ（フロントビルド用）
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: npm install & build
        run: |
          npm ci
          npm run build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: コードをチェックアウト
        uses: actions/checkout@v3

      - name: デプロイ用 SSH キー設定
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Generate .env on CI
        run: |
          cat <<EOF > .env
          FORWARD_DB_PORT=13306
          FORWARD_MAILPIT_PORT=11025
          APP_PORT=3001

          APP_NAME="TODO Reminder App"
          APP_ENV=${{ secrets.APP_ENV }}
          APP_KEY=${{ secrets.APP_KEY }}
          APP_DEBUG=false
          APP_URL=${{ secrets.APP_URL }}

          SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}

          LOG_CHANNEL=stack
          LOG_DEPRECATIONS_CHANNEL=null
          LOG_LEVEL=warning

          DB_CONNECTION=mysql
          DB_HOST=${{ secrets.DB_HOST }}
          DB_PORT=3306
          DB_DATABASE=${{ secrets.DB_DATABASE }}
          DB_USERNAME=${{ secrets.DB_USERNAME }}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}

          BROADCAST_DRIVER=log
          CACHE_DRIVER=file
          FILESYSTEM_DISK=local
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120

          MAIL_MAILER=smtp
          MAIL_HOST=mailpit
          MAIL_PORT=1025
          MAIL_USERNAME=null
          MAIL_PASSWORD=null
          MAIL_ENCRYPTION=null
          MAIL_FROM_ADDRESS="hello@example.com"
          MAIL_FROM_NAME="${APP_NAME}"

          VITE_APP_NAME="${APP_NAME}"
          EOF

      - name: Deploy to VPS via rsync
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          rsync -az --delete \
            ./ $VPS_USER@$VPS_HOST:/var/www/todo-reminder-app

      - name: リモートでキャッシュクリア等
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          ssh $VPS_USER@$VPS_HOST "
            cd /var/www/todo-reminder-app &&
            composer install --no-interaction --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan config:cache &&
            php artisan route:cache
          "
